# run information
METHODOLOGY: afno
SEED: 1999
DATA_FILE: basic_heat_dataset.npy

# dataloader info
TIME_STEPS_IN: 7
TIME_STEPS_OUT: 7
BATCH_SIZE: 16
TIME_INT: 10
USE_GRID: True

# model information
PATCH_SIZE: [5, 5]
LATENT_DIMS: 16
NUM_BLOCKS: 1
DROP_RATE: 0.2
DROP_PATH_RATE: 0.2
MLP_RATIO: 1
DEPTH: 1

# train information
EPOCHS: 5

OPTIMIZER: 
  KIND: adam
  LEARNING_RATE: 0.001

SCHEDULER:
  KIND: reducer
  FACTOR: 0.1
  PATIENCE: 1