GRAPH_LOADER: True

# general
BATCH_SIZE: 16
LATENT_DIMS: 16
DEPTH: 3
LOSS: LPLOSS

# fno stuff
MODES1: 12
MODES2: 12

# gno stuff
EDGE_RADIUS: 0.1
EDGE_DROPOUT: 0.4
KERNEL_DIMS: 16
GRAPH_PASSES: 2

ADD_INIT_TO_EDGE: True
