GRAPH_LOADER: True

# general
BATCH_SIZE: 10
LATENT_DIMS: 20
DEPTH: 4
LOSS: LPLOSS
EPOCHS: 150

# fno stuff
MODES1: 12
MODES2: 12

# gno stuff
EDGE_RADIUS: 0.1
EDGE_DROPOUT: 0.3
KERNEL_DIMS: 16
GRAPH_PASSES: 2

ADD_INIT_TO_EDGE: True