# general
BATCH_SIZE: 8
LATENT_DIMS: 20
DEPTH: 3
LOSS: LPLOSS
EPOCHS: 250

# fno stuff
MODES1: 12
MODES2: 12

# gno stuff
EDGE_RADIUS: 0.1
EDGE_DROPOUT: 0.3
KERNEL_DIMS: 16
GRAPH_PASSES: 1

ADD_INIT_TO_EDGE: True


