# run information
METHODOLOGY: persistance
SEED: 1999
DATA_FILE: basic_heat_dataset.npy

# DATA_FILE: heat_sinusoidal_init_varying_diffusivity_periodic_boundaries.npy

# dataloader info
TIME_STEPS_IN: 1
TIME_STEPS_OUT: 28
BATCH_SIZE: 16
TIME_INT: 1
USE_GRID: True

EPOCHS: 1

NORMALIZER: range

OPTIMIZER: 
  KIND: adam
  LEARNING_RATE: 0.001

SCHEDULER:
  KIND: reducer
  FACTOR: 0.1
  PATIENCE: 1