# general
BATCH_SIZE: 8
LATENT_DIMS: 26
DEPTH: 3
LOSS: LPLOSS
EPOCHS: 250

# fno stuff
MODES1: 8
MODES2: 10

# gno stuff
EDGE_RADIUS: 0.1
EDGE_DROPOUT: 0.4
GRAPH_PASSES: 2

LEARNING_RATE: 0.001
ADD_INIT_TO_EDGE: True


