# general
BATCH_SIZE: 8
LATENT_DIMS: 32
DEPTH: 3
LOSS: LPLOSS
EPOCHS: 300

# fno stuff
MODES1: 8
MODES2: 12

# gno stuff
EDGE_RADIUS: 0.05
EDGE_DROPOUT: 0.3
GRAPH_PASSES: 3

LEARNING_RATE: 0.0001
ADD_INIT_TO_EDGE: True


