# general
BATCH_SIZE: 8
LATENT_DIMS: 32
DEPTH: 3
LOSS: LPLOSS
EPOCHS: 250

# fno stuff
MODES1: 12
MODES2: 12

# gno stuff
EDGE_RADIUS: 0.1
EDGE_DROPOUT: 0.3
GRAPH_PASSES: 3

LEARNING_RATE: 0.001
ADD_INIT_TO_EDGE: True


