# run information
METHODOLOGY: fno
SEED: 1999
DATA_FILE: basic_heat_dataset.npy
# DATA_FILE: heat_sinusoidal_init_varying_diffusivity_periodic_boundaries.npy

# dataloader info
TIME_STEPS_IN: 7
TIME_STEPS_OUT: 28
BATCH_SIZE: 16
TIME_INT: 1
USE_GRID: False

GRAPH_DATA_LOADER: True

# model information
LATENT_DIMS: 16
NEIGHBORS: radial
DROP_RATE: 0.2
MLP_RATIO: 1
DEPTH: 4

# train information
EPOCHS: 100

OPTIMIZER: 
  KIND: adam
  LEARNING_RATE: 0.001

SCHEDULER:
  KIND: reducer
  FACTOR: 0.1
  PATIENCE: 1