burgers_64_x_non_period_y_non_period_fixed_nu.npy
burgers_64_x_non_period_y_non_period_varying_nu.npy
burgers_64_x_period_y_period_varying_nu.npy
diffusion_varying_sinusoidal_init_fixed_diffusivity_non_periodic_boundaries.npy
diffusion_varying_sinusoidal_init_varying_diffusivity_non_periodic_boundaries.npy
diffusion_varying_sinusoidal_init_varying_diffusivity_periodic_boundaries.npy