# run information
SEED: 1999
# data information
GRAPH_LOADER: False
DATA_MODE: PDE
TIME_STEPS_IN: 10
TIME_STEPS_OUT: 10
BATCH_SIZE: 20
NORMALIZATION: none
# model information
LOSS: MSE
# train information
EPOCHS: 250
LEARNING_RATE: 0.001
OPTIMIZER: 
  KIND: adam
SCHEDULER:
  KIND: cosine
  # PATIENCE: 2
  # FACTOR: 0.5