# run information
SEED: 1999
# data information
DATA_READER: MAT
SINGLE_SAMPLE_LOADER: True
GRAPH_LOADER: False
TIME_STEPS_IN: 10
TIME_STEPS_OUT: 20
BATCH_SIZE: 16
TIME_INTERVAL: 1
NORMALIZATION: none
# model information
LOSS: LPLOSS
# train information
EPOCHS: 50
LEARNING_RATE: 0.01
OPTIMIZER: 
  KIND: adam
SCHEDULER:
  KIND: reducer
  FACTOR: 0.1
  PATIENCE: 1