# run information
SEED: 1999
# data information
DATA_READER: NPZ
SINGLE_SAMPLE_LOADER: False
GRAPH_LOADER: False
TIME_STEPS_IN: 7
TIME_STEPS_OUT: 28
BATCH_SIZE: 16
TIME_INTERVAL: 1
NORMALIZATION: none
# model information
LOSS: MSE
# train information
EPOCHS: 2
LEARNING_RATE: 0.01
OPTIMIZER: 
  KIND: adam
SCHEDULER:
  KIND: reducer
  FACTOR: 0.1
  PATIENCE: 1