# run information
SEED: 1999
# data information
TIME_STEPS_IN: 10
TIME_STEPS_OUT: 10
BATCH_SIZE: 16
NORMALIZATION: gaussian
# model information
LOSS: MSE
# train information
EPOCHS: 250
LEARNING_RATE: 0.001
OPTIMIZER: 
  KIND: adam
SCHEDULER:
  KIND: cosine

DATA_FILE: heat_equation_non_periodic.h5
# DATA_FILE: heat_equation_periodic.h5
# DATA_FILE: NavierStokes_V1e-5_N1200_T20.mat

DATA_MODE: CUST_PDE
# DATA_MODE: PDE
