# run information
METHODOLOGY: conv_lstm
SEED: 1999
DATA_FILE: basic_heat_dataset.npy

# dataloader info
TIME_STEPS_IN: 7
TIME_STEPS_OUT: 7
BATCH_SIZE: 16
TIME_INT: 10
USE_GRID: True

# model information
LATENT_DIMS: 8
PROJ_KERNEL_SIZE: 5
KERNEL_SIZE: 3
DEPTH: 1

# train information
EPOCHS: 50

OPTIMIZER: 
  KIND: adam
  LEARNING_RATE: 0.001

SCHEDULER:
  KIND: reducer
  FACTOR: 0.1
  PATIENCE: 1